!--------------------------------------------------------- -*- fortran -*- ----
! file: code/inputOutput/input.f90
&input
  numEnsembles = 200,    ! number of ensembles
  eventtype    = 200,    ! transport given particle
  delta_T      = 0.05,   ! time step size
  numTimeSteps = 200,    ! number of time steps
  num_energies = 1,
  num_runs_sameEnergy = 1,
  length_perturbative = 10000,
  freezeRealParticles = T,
  printParticleVectors = T,
  LRF_equals_CALC_frame = T,
  path_To_Input = "~/GiBUU/buuinput",
/

! file: code/database/particleProperties.f90
&initDatabase
  propagationSwitch = 0,   ! 0=all resonances with more than 1 star, 1=only delta&nucleon, 2=only nucleons
/

! file: code/numerics/random.f90
&initRandom
  Seed = 223214,   ! seed for the random number
/

! file: code/density/nucleus.f90
&target
  Target_A = 12,
  Target_Z =  6,
  fermiMotion = T,
  densitySwitch_static = 2,   ! 1=Woods-Saxon, 2=according NPA 554 (Oset)
/

! file: code/density/density.f90
&initDensity
  densitySwitch = 2,  ! 1=dynamic density according to testparticle density, 2=analytic density prescription
/

! file: code/density/pauliBlocking.f90
&initPauli
  pauliSwitch = 2,   ! 1=dynamic, 2=analytic
/

! file: code/propagation/propagation.f90
&Propagation
  RungeKuttaOrder = 2,   ! 1=first order Runge-Kutta, 2=second order Runge-Kutta
/

! file: code/width/offShellPotential.f90
&OffShellPotential
  useOffShellPotentialBaryons = T,
  max_offshellparameter = 10.
/

! file: code/width/baryonWidthMedium.f90
&width_Baryon
  mediumSwitch       = T,
  mediumSwitch_Delta = F,
  mediumSwitch_coll  = T,
/

! file: code/init/initTransportGivenParticle.f90
&TransportGivenParticle
  particle_ID = 1,
  charge      = 1,
  position(1:3) = 0., 0., 0.,
  threemomentum(1:3) = 0.5, 0.5, 0.5,
  mass = -1.1341748636563400,
/

! file: code/collisions/collisionTerm.f90
&collisionterm
  oneBodyProcesses   = F,
  twoBodyProcesses   = F,
  threeBodyProcesses = F,
/
