!--------------------------------------------------------- -*- fortran -*- ----
! sample jobcard for antiproton-induced reactions
! relevant, e.g., for the PANDA experiment
! using perturbative particles
!------------------------------------------------------------------------------
! please visit the GiBUU homepage for further information:
! https://gibuu.hepforge.org
! for details please contact:
! * Alexei.Larionov@theo.physik.uni-giessen.de
! * Theodoros.Gaitanos@theo.physik.uni-giessen.de
!------------------------------------------------------------------------------

! file: code/inputOutput/input.f90
&input
      eventtype       =         300 ! hadron induced
      numEnsembles    =        1000
      numTimeSteps    =         100
      num_runs_SameEnergy=       10 ! number of runs per energy

      time_max        =       500.0 !
      timeForOutput   =        80.0 !
      timeSequence    =        30.0

      freezeRealParticles =   T
      length_perturbative =   1000

!      DoPrLevel(1) = .FALSE.
!      DoPrLevel(2) = .FALSE.

      path_To_Input   = '~/GiBUU/buuinput'
/

! file: code/init/initHadron.f90
&hadron
      impactParameter =   7.60 ! [fm] (<0: Monte-Carlo choice)
!      bRaiseFlag      = F     ! if true, increase impact parameter b
!      deltaB          = 0.25  ! value to increase b with
!      nRunsPerB       = 1     ! number of runs per b value
      perturbative    = T     ! is projectile a perturbative particle?
      numberParticles =   100 ! #projectiles per ensemble
      particleId      =     1 ! projectile: id
      antiParticle    = T     ! projectile: antiparticle flag
      particleCharge  =    -1 ! projectile: charge
      ekin_lab        =  3.238691 ! projectile: kinetic energy [GeV]
!      E_bind          =     0 ! binding energy [GeV]
!      iniType         =     0 ! 0: default, 1: p&x gaussian, 2: x gaussian
      zChoice         =     2 ! 1: distance form surface, 2: fixed z
!      delta           = 0.500 ! distance [fm] (see code doku)
      deltaZ          = 1.00  ! distance [fm] (see code doku)
!      width           =  1.00 ! Width of a gaussian density profile [fm].
!      debug           = F     ! additional debug output
/

! file: code/density/nucleus.f90
&target
!      fermiMotion = .FALSE.
!      target_Z=  1, target_A=  1 ! proton,neutron, deuterium
!      target_Z=  4, target_A=  9, densitySwitch_Static=4 ! Be
!      target_Z=  6, target_A= 12, densitySwitch_Static=4 ! C
!      target_Z=  6, target_A= 12 ! C
!      target_Z=  7, target_A= 14 ! N
!      target_Z= 10, target_A= 20 ! Ne
      target_Z= 13, target_A= 27, densitySwitch_Static=2 ! Al
!      target_Z= 16, target_A= 32 ! S
!      target_Z= 20, target_A= 40 ! Ca
!      target_Z= 26, target_A= 56 ! Fe
!      target_Z= 29, target_A= 64 ! Cu
!      target_Z= 36, target_A= 84 ! Kr
!      target_Z= 41, target_A= 93, densitySwitch_Static=8 ! Nb
!      target_Z= 54, target_A=131 ! Xe
!      target_Z= 82, target_A=208 ! Pb
/

! file: code/database/particleProperties.f90
&initDatabase
      propagationSwitch = 0 ! 0=all resonances with more than 1 star
/

! file: code/numerics/random.f90
&initRandom
      SEED=777                ! Seed for the random number
/

! file: code/rmf/RMF.f90
&RMF_input
      RMF_flag        = F
      grad_flag       = T
      N_set           = 2
      fact_pbar       =  0.220000
      fact_hyp        =  0.666666
      fact_antihyp    =  0.666666
      fact_Xi         =  0.333333
      fact_antiXi     =  0.333333
      fact_kaon       =  0.333333
/

! file: code/density/density.f90
&initDensity
      densitySwitch   = 2                 ! 2: static density
      gridSize        = 10.0, 10.0, 10.0
      gridPoints      = 20,   20,   20
/

! file: code/potential/baryonPotential.f90
&baryonPotential
      EQS_TYPE        =  0
/

! file: code/propagation/propagation.f90
&Propagation
      UseHadronic             = F
      Mode                    = 1
/

! file: code/collisions/collisionTerm.f90
&collisionterm
      threeBodyProcesses = F
      energyCheck        =  0.100
      maxOut             =     30
      annihilationTime   =  0.000
/

! file: code/collisions/twoBodyReactions/master_2Body.f90
&master_2body
      mesonMesonScattering    = F
      usePythia               = 0
      useManni                = F
      coarse                  = 2.000, 4.000, 4.000
      bmax_nucleonNucleon     = 2.000
      bmax_baryonMeson        = 4.000
/

! file: code/analysis/HeavyIonAnalysis.f90
&HICanalysis_Input
      flag_outputPert = T
/

! file: code/collisions/phaseSpace/winkelVerteilung.f90
&angular_distribution
      deltaPWave              = F
      rho_pipi_nonIsotropic   = F
      pionNucleon_backward    = F
/

! file: code/collisions/twoBodyReactions/baryonBaryon/barAntiBar.f90
&barAntiBar_input
      fact_LambdaBar  =        1.0
      fact_JPsi       =   100000.0
      fact_JPsi_width =      100.0
/

! file: code/collisions/insertion.f90
&insertion
      minimumEnergy   =  2.000
/

! file: ./density/pauliBlocking.f90
&initPauli
      pauliSwitch     = 2 ! 0: no Pauli blocking, 1: dynamic, 2: analytic
/
